resources moved with migrationhierarchy
dana-team/hns pull request #96
Opened 2023-08-18 21:38 UTC by mzeevi

Fixes #22. With this PR, resources are now moved together with the subnamespace when a MigrationHierarchy is made. In addition, some fixes and additions were made to the MigrationHierarchy webhook, and the logging has been changed back from ecs to regular logging

2023-08-18 21:43 UTC, mzeevi commented
I deleted the `vendor` directory so there are a ton of files changed...

/assign @liadlauber

2023-08-24 17:10 UTC, mzeevi commented
Updated @liadlauber

2023-08-29 07:05 UTC, liadlauber requested changes
Overall, it looks good to me. make the necessary fixes and resubmit the PR.

2023-08-31 18:08 UTC, mzeevi commented on internals/controllers/migrationhierarchy/migrationhierarchy_status.go
> +func (r *MigrationHierarchyReconciler) updateMHSuccessStatus(upqObject *utils.ObjectContext) error {
Yeah good shout, changed it

2023-08-31 18:12 UTC, mzeevi commented on main.go
> +		Development: true,
Yeah this is by default how it's done in kubebuilder https://github.com/kubernetes-sigs/kubebuilder/blob/3ac13147e445b92be68365c39da4b5fc22614a34/docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go#L79-L80

2023-08-31 18:18 UTC, mzeevi commented on internals/controllers/migrationhierarchy/migrationhierarchy_resources.go
> +func createUpdateQuota(mhObject *utils.ObjectContext, upqName, sourceNS, destNS string, resources corev1.ResourceQuotaSpec) error {
Not sure I understand the problem?

2023-08-31 18:20 UTC, mzeevi commented on internals/controllers/migrationhierarchy/migrationhierarchy_resources.go
> +		return ctrl.Result{Requeue: true}, nil
Added the comment in another place

2023-08-31 18:22 UTC, mzeevi commented on internals/utils/quota_utils.go
> +	rootNSName := GetNSDisplayNameSlice(ns)[0]
I don't use this function actually so it can be removed

2023-09-01 03:58 UTC, liadlauber commented on internals/controllers/migrationhierarchy/migrationhierarchy_resources.go
> +func createUpdateQuota(mhObject *utils.ObjectContext, upqName, sourceNS, destNS string, resources corev1.ResourceQuotaSpec) error {
sometimes you use 'UpdateQuota,' while sometimes you use 'UPQ.' It's not a big deal, I can live with it.

2023-09-01 04:09 UTC, liadlauber approved these changes

2023-09-01 06:53 UTC, liadlauber commented
/lgtm /approve

2023-09-01 06:55 UTC, liadlauber commented
/lgtm

2023-09-01 06:56 UTC, merged